### ISSUE TITLE
nomisa using non-nomisma.org URL.

### ISSUE THREAD

**Issue by Msch0150** [nomisma/framework#30]
I assume that "nomisma framework" was never designed to run under an other url.

Anyhow:

Setup nomisma using a non-nomisma url (example: http://192.168.178.75:10400/orbeon/nomisma)
Create new concept > id (vienne) > Type (Mint) >Import Wikipedia > check all > URL (https://en.wikipedia.org/wiki/Vienne,_Is%C3%A8re) > import
Preffered Label "Vienne" for English > Definition "Mint at the ancient site of Vienna." > Save

1. You see 
"Edit ID (http://nomisma.org/id/vienne)"
but I would expect 
"Edit ID (http://192.168.178.75:10400/orbeon/nomisma/id/vienne)"

2. You see 
"Miscellaneous Fields  (Location http://nomisma.org/id/vienne#this)"
but I would expect
"Miscellaneous Fields  (Location http://192.168.178.75:10400/orbeon/nomisma/id/vienne#this)"

3. You see
"Geography (http://nomisma.org/id/vienne#this)"
but I would expect
"Geography (Location http://192.168.178.75:10400/orbeon/nomisma/id/vienne#this)"

4. 
Check the created id: http://192.168.178.75:10400/orbeon/nomisma/id/vienne
You yee
skos:inScheme http://nomisma.org/id/
geo:location http://nomisma.org/id/vienne#this
Probably due to 1,2,3.

5.
Use numishare and add a coin via xml Upload.
...
            <geographic>
                <geogname xlink:type="simple" xlink:role="mint" xlink:href="http://192.168.178.75:10400/orbeon/nomisma/id/vienne">Vienna</geogname>
            </geographic>
...
Info (if not already known): Vienna is the ancient name of the roman mint in Gallia (and not the capital of Austria).

Check the coin in numishare and select the language "en" or "de". Usually numishare displays the name for the selected language, in these cases "Vienne" but it always displays it as "Vienna".
Maybe this behavior is related to 1,2,3.

Additional info:
I setup a local nomisma as a workaround until the mint "vienne" is setup officially in nomisma.org.
So, the relevant issue is number 5.

**Comment by ewg118** [comment]
No, the Nomisma framework has too many URLs hard-coded into the XForms back-end. I do not suggest that you take this approach to minting your own identifiers. We are aware that there is no ID for Roman Vienna. It will be created as soon as the moratorium on new Nomisma IDs has been lifted after testing the new data provenance system, and OCRE will be updated to link to Roman Vienna, not http://nomisma.org/id/vienna, which is intended to be the modern mint of Vienna, Austria.

**Comment by Msch0150** [comment]
Thanks for the very fast response.
