### ISSUE TITLE
Can't delete dcterms:isPartOf from nm:hispania_citerior

### ISSUE THREAD

**Issue by sfsheath** [nomisma/framework#31]
http://nomisma.org/id/hispania_citerior shows  "dcterms:isPartOf nm:hispania". But that isn't reflected in the editor so I can't delete it. I have added a skos:broader and that is showing in the public site.

**Comment by ewg118** [comment]
The handling of dcterms:isPartOf that don't link to field of numismatics URIs is solved. In fact, there's tighter validation requiring them to be deleted before the file can be saved.
