### ISSUE TITLE
Doc!

### ISSUE THREAD

**Issue by lbugnon** [nomisma/framework#32]
Please add documentation! it would be great to include Nomisma concepts and ontology in a webapp, but I didn't found a guide/manual to do so.

**Comment by lbugnon** [comment]
Well, I figured out that I could  download the RDF for each concept to the server and then read content on demand, but I'm not sure if it is the way to do it. Is there any API for this?

**Comment by ewg118** [comment]
Can you explain what exactly you are attempting to do? There are bulk downloads of Nomisma RDF, but you can also request data from single IDs from a URL or content negotiation.
