### ISSUE TITLE
Data Dumps generate an error "...:43 Stack trace: #0 {main} thrown in ..."

### ISSUE THREAD

**Issue by Msch0150** [nomisma/framework#38]
Maybe this is an issue of the exporting party:

https://nomisma.org/datasets then click on any "data dump" which uses "mk_edit". Examples:

Berlin: https://ikmk.smb.museum/mk-edit/coin_export/43/MK-B-43-nomisma.rdf

gives an error: "Fatal error: Uncaught Error: Call to undefined function getSettings() in /data/www/001-ikmk/mk-edit/coin_export/index.php:43 Stack trace: #0 {main} thrown in /data/www/001-ikmk/mk-edit/coin_export/index.php on line 43"

Bochum: http://ikmk.ruhr-uni-bochum.de/mk-edit/coin_export/3/MK-BO-3-nomisma.rdf

Fatal error: Uncaught Error: Call to undefined function getSettings() in /var/www/html/mk-edit/coin_export/index.php:43 Stack trace: #0 {main} thrown in /var/www/html/mk-edit/coin_export/index.php on line 43

Probably all parties which use the software from Berlin (ikmk) have the issue. But maybe they have just changed a link and the nomisma page needs to be updated. Please let me know what you think. Then I might try to find a responsible person.

**Comment by ewg118** [comment]
This is something wrong with their code. If any links have been changed, Karsten Dahmen at MK Berlin needs to unload the current exports and reload them.

**Comment by Msch0150** [comment]
Contacted Karten Dahmen. It is fixed now.
